server:
  # Application running port
  port: 8085

openapi:
  dev:
    url: http://localhost:8085

spring:
  h2:
    console:
      # Allow H2 DB to be accessed via browser and via Java application
      enabled: true
      # Database server path
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/h2/bookdb
    driverClassName: org.h2.Driver
  #    username: root
  #    password: psw
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Update, create, validate, none
      format_sql: true