spring:
  profiles:
    active: local
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
springdoc:
  api-docs:
    enabled: true
  path: /v3/api-docs
  # Enable/Disable swagger-ui
  # swagger-ui custom path
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
#  show-actuator: true

# Actuator configuration
management:
  endpoints:
    shutdown:
      enabled: true
    jmc:
      exposure:
        # If kibana dashboard is connected then it will stream metrics continuously then use this
        include: health,metrics,info,env,beans
    web:
      exposure:
        # If we want to see metrics on web page this use this.
        include: health,metrics,info,env,beans,configprops
  metrics:
    enabled: true

app:
  jwtSecret: c29tZSByYW5kb20gc2hpdCBjb250ZW50YXNkZ2FzZGdhc2RnYXNkZ2FzZGdhc2RnYXNkZ2FzZGdhc2RnYXNkZ2FzZGc
  jwtExpirationInMs: 3600000