server:
  port: 8085
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booksdb
    username: root
    password: psw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Update, create, validate, none
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        time_zone: UTC # Set database timezone
